rem *****UK TIMES standard outputs tool*****
rem DOS Batch file to construct SQL queries, run the code, amalgamate the results and tidy up (delete) the intermediate stages
rem version as filename. By Fernley Symons 8:02 PM 12 January, 2016
rem works by: 
rem 1) constructing SQL code file to create temp files from TIMES runs (creates one script entry for each file)
rem 2) adding analysis SQL to generate summaries which are output to CSVs
rem 3) amalgamates the CSVs
rem 4) deletes the intermediate CSVs leaving a single output file
rem By Fernley Symons
rem ***********
rem 9:34 PM 19 January, 2016 Correction of error in new vehicles capacity script
rem 2:04 PM 01 February, 2016; addition of whole vehicle stock capacity
rem 2:58 PM 04 February, 2016; addition of new vehicle emissions intensity
rem 1:39 PM 08 February, 2016; correction of new vehicle emissions intensity
rem 3:30 PM 16 February, 2016; a slew of new queries, refactored code, re-ordered queries. Baseline version for git:-replaces v18
rem ***********
rem The following allows us to insert text which is otherwise outlawed in DOS:
setlocal enableDelayedExpansion
rem Things to bear in mind:
rem if '%' is part of a sql query (e.g. "like 'x%'), then % needs to be doubled "like 'x%%'"
rem Other characters (|, <, > etc) need to be escaped in a similar way with ^:- ^| etc
rem can't have very long lines - need to break statements
rem filename at end of line, no spaces afterwards
rem delete the SQL script if it exists - code below (re-) generates it.
IF EXIST VedaBatchUpload.sql del /F VedaBatchUpload.sql
rem need to define some variables which contain DOS reserved words. These are replaced by the preprocessor in the script:
set "texta=IF"
set "textb=IF NOT"
set "textc=~"
set "textd=^"
rem this block creates the 2 temp table definitions. First stores the unformatted data from the VD file, second parses this into fields and inserts into the "vedastore" table against which the 
rem queries are run.
echo CREATE temp TABLE !textb! EXISTS vedastore( tablename varchar(100), id serial, attribute varchar(50), commodity varchar(50), process varchar(50), period varchar(50), region varchar(50), vintage varchar(50), timeslice varchar(50), userconstraint varchar(50), pv numeric ); drop table !texta! exists veda; create temp table veda( id serial, stuff varchar(1000) ); >> VedaBatchUpload.sql
rem the following creates a block of sql for each VD file to upload it, delete the header rows and break the entries into fields
for /f "delims=|" %%i in ('dir /b *.vd') do echo delete from veda; ALTER SEQUENCE veda_id_seq RESTART WITH 1; copy veda (stuff) from '%%~fi'; insert into vedastore (tablename, attribute ,commodity ,process ,period ,region ,vintage ,timeslice ,userconstraint ,pv) select '%%~ni', trim(both '"' from a[1]), trim(both '"' from a[2]), trim(both '"' from a[3]), trim(both '"' from a[4]), trim(both '"' from a[5]), trim(both '"' from a[6]), trim(both '"' from a[7]), trim(both '"' from a[8]), cast(a[9] as numeric) from ( select string_to_array(stuff, ',') from veda order by id offset 13 ) as dt(a); >> VedaBatchUpload.sql
rem first cross-tabs sql is here. This is dummy imports;
echo /* *Dummy imports by table* */COPY ( select 'dummies' ^|^| '^|' ^|^| tablename ^|^| '^|' ^|^| 'Cost_Act' ^|^| '^|' ^|^| 'various' ^|^| '^|various'::varchar(300) "id", 'dummies'::varchar(300) "analysis", tablename, 'Cost_Act'::varchar(50) "attribute", 'various'::varchar(50) "commodity", 'various'::varchar(50) "process", sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from vedastore where process like 'IMP%%Z' and attribute = 'Cost_Act' group by tablename order by tablename, analysis ) TO '%~dp0dummiesout.csv' delimiter ',' CSV HEADER; >> VedaBatchUpload.sql
rem All GHG emissions
echo /* *All GHG emissions* */COPY ( select 'ghg_all^|' ^|^| tablename ^|^| '^|Var_FOut^|' ^|^| commodity ^|^| '^|all'::varchar(300) "id", 'ghg_all'::varchar(50) "analysis", tablename, 'Var_FOut'::varchar(50) "attribute", commodity, 'all'::varchar(50) "process", sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from vedastore where attribute='VAR_FOut' and commodity in('GHG-ETS-NO-IAS-NET', 'GHG-ETS-NO-IAS-TER', 'GHG-ETS-YES-IAS-NET', 'GHG-ETS-YES-IAS-TER', 'GHG-NO-IAS-YES-LULUCF-NET', 'GHG-NO-IAS-YES-LULUCF-TER', 'GHG-NON-ETS-YES-LULUCF-NET', 'GHG-NON-ETS-YES-LULUCF-TER', 'GHG-YES-IAS-YES-LULUCF-NET', 'GHG-YES-IAS-YES-LULUCF-TER') group by tablename, commodity order by tablename, commodity ) TO '%~dp0GHGOut.csv' delimiter ',' CSV; >> VedaBatchUpload.sql
rem GHG emissions by sector
echo /* *GHG emissions by sector* */COPY ( select analysis ^|^| '^|' ^|^| tablename ^|^| '^|' ^|^| attribute ^|^| '^|' ^|^| commodity ^|^| '^|' ^|^| process::varchar(300) "id", analysis, tablename,attribute, commodity, process, sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from ( select 'all'::varchar(50) "process", period, pv, tablename, attribute, case   when commodity in('PRCCO2P', 'PRCCH4N', 'PRCCH4P', 'PRCN2ON', 'PRCN2OP') then 'various'   else commodity end as "commodity", case when attribute='VAR_FIn' then 'ghg_sec-traded-emis-ets' when commodity in('GHG-ELC','GHG-IND-ETS','GHG-RES-ETS','GHG-SER-ETS','GHG-OTHER-ETS','GHG-TRA-ETS-NO-IAS','GHG-IAS-ETS', 'GHG-IAS-NON-ETS','Traded-Emission-ETS','GHG-IND-NON-ETS','GHG-RES-NON-ETS','GHG-SER-NON-ETS','GHG-TRA-NON-ETS-NO-IAS', >> VedaBatchUpload.sql
echo  'GHG-AGR-NO-LULUCF','GHG-OTHER-NON-ETS','GHG-LULUCF','Traded-Emission-Non-ETS','GHG-ELC-CAPTURED','GHG-IND-ETS-CAPTURED', 'GHG-IND-NON-ETS-CAPTURED','GHG-OTHER-ETS-CAPTURED') then 'ghg_sec-main-secs' when commodity in('PRCCO2P', 'PRCCH4N', 'PRCCH4P', 'PRCN2ON', 'PRCN2OP') then 'ghg_sec-prc-non-ets' when commodity ='PRCCO2N' then 'ghg_sec-prc-ets' end as "analysis" from vedastore where (attribute='VAR_FOut' and commodity in('GHG-ELC','GHG-IND-ETS','GHG-RES-ETS','GHG-SER-ETS','GHG-OTHER-ETS','GHG-TRA-ETS-NO-IAS','GHG-IAS-ETS','GHG-IAS-NON-ETS','Traded-Emission-ETS','GHG-IND-NON-ETS','GHG-RES-NON-ETS','GHG-SER-NON-ETS','GHG-TRA-NON-ETS-NO-IAS','GHG-AGR-NO-LULUCF','GHG-OTHER-NON-ETS','GHG-LULUCF','Traded-Emission-Non-ETS','GHG-ELC-CAPTURED','GHG-IND-ETS-CAPTURED','GHG-IND-NON-ETS-CAPTURED','GHG-OTHER-ETS-CAPTURED','PRCCO2P','PRCCH4N','PRCCH4P','PRCN2ON','PRCN2OP','PRCCO2N')) or (attribute='VAR_FIn' and commodity='Traded-Emission-ETS') ) a where analysis ^<^>'' group by id, analysis,tablename, attribute, commodity,process order by tablename, analysis, attribute, commodity ) TO '%~dp0GHGsectorOut.csv' delimiter ',' CSV; >> VedaBatchUpload.sql
rem CHP emissions from electricity generation
echo /* CHP emissions from electricity generation* */COPY ( select analysis ^|^| '^|' ^|^| tablename ^|^| '^|VAR_FOut^|' ^|^| commodity ^|^| '^|' ^|^| process::varchar(300) "id", analysis, tablename,attribute, commodity,process, sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from ( select '*CHP*'::varchar(50) "process",period,pv, case when commodity in ('GHG-IND-NON-ETS-CAPTURED','GHG-OTHER-ETS-CAPTURED','GHG-IND-ETS-CAPTURED') then 'chp-sav_emis'::varchar(25) when commodity in ('GHG-IND-ETS','GHG-IND-NON-ETS','GHG-OTHER-ETS','GHG-OTHER-NON-ETS') or commodity like 'PRCCH4%%' or commodity like   'PRCCO2%%' or commodity like 'PRCN2O%%' or commodity like 'GHG-RES-%%' or commodity like 'GHG-SER-%%' then 'chp-out_emis'::varchar(25) end as "analysis", tablename, attribute,'various'::varchar(50) "commodity" from vedastore where attribute = 'VAR_FOut' and (process like 'I%%CHP%%' or process like 'P%%CHP%%' or process like 'R%%CHP%%' or process like 'S%%CHP%%' or process like 'U%%CHP%%') ) a where analysis ^<^>'' group by id, analysis,tablename, attribute, commodity,process order by tablename, analysis, attribute, commodity ) TO '%~dp0CHPelecEmis.csv' delimiter ',' CSV; >> VedaBatchUpload.sql
rem Electricity generation by source
echo /* *Electricity generation by source* */select process, period,pv, case when attribute = 'VAR_FOut' and commodity in('ELCGEN','INDELC','RESELC','RESHOUSEELC','SERBUILDELC','SERDISTELC','SERELC') and (process like 'I%%CHP%%' or process like 'P%%CHP%%' or process like 'R%%CHP%%' or process like 'S%%CHP%%' or process like 'U%%CHP%%') then 'elec-gen_chp'::varchar(50) when commodity = 'ELCGEN' and attribute = 'VAR_FOut' then case when process in ('ESTWWST00','EPOLWST00', 'EBIOS00','EBOG-LFE00','EBOG-SWE00','EMSW00','EBIOCON00', 'ESTWWST01','EBIO01','EBOG-ADE01','EBOG-LFE01','EBOG-SWE01','EMSW01') then 'elec-gen_bio'::varchar(50) when process ='EBIOQ01' then 'elec-gen_bio-ccs'::varchar(50) when process in ('ECOA00','ECOABIO00', 'ECOARR01') then 'elec-gen_coal'::varchar(50) when process in ('ECOAQ01','ECOAQDEMO01') then 'elec-gen_coal-ccs'::varchar(50) when process in ('EHYGCCT01','EHYGOCT01') then 'elec-gen_h2'::varchar(50) when process in ('ENGACCT00','ENGAOCT00','ENGACCTRR01','ENGAOCT01') then 'elec-gen_nga'::varchar(50) when process in ('ENGACCTQ01','ENGACCTQDEMO01') then 'elec-gen_nga-ccs'::varchar(50) when process in ('ENUCPWR00','ENUCAGRN00','ENUCAGRO00','ENUCPWR101','ENUCPWR102') then 'elec-gen_nuclear'::varchar(50) when process in ('EWNDOFF00','EWNDOFF101','EWNDOFF201','EWNDOFF301') then 'elec-gen_offw'::varchar(50) when process in ('EWNDONS00','EWNDONS101','EWNDONS201','EWNDONS301','EWNDONS401','EWNDONS501', 'EWNDONS601','EWNDONS701','EWNDONS801','EWNDONS901') then 'elec-gen_onw'::varchar(50) when process ='EHFOIGCCQ01' then 'elec-gen_other-ccs'::varchar(50) when process in ('EOILL00','EOILS00','EMANOCT00','EMANOCT01','EOILS01','EOILL01','EHFOIGCC01') then 'elec-gen_other-ff'::varchar(50) when process in >> VedaBatchUpload.sql
echo ('EHYD00','EHYD01','EGEO01','ETIR101','ETIB101','ETIS101','EWAV101') then 'elec-gen_other-rens'::varchar(50) when process in ('ESOL00','ESOLPV00','ESOL01','ESOLPV01') then 'elec-gen_solar'::varchar(50) when process like 'ELCIE%%' or process like 'ELCII%%' then 'elec-gen_imports'::varchar(50) end when commodity = 'ELCGEN' and attribute = 'VAR_FIn' then case when process like 'ELCEE%%' or process like 'ELCEI%%' then 'elec-gen_exports'::varchar(50) when process like 'EWSTHEAT-OFF%%' then 'elec-gen_waste-heat-penalty'::varchar(50) end end as "analysis", tablename, attribute into temp elecgen from vedastore where commodity in('ELCGEN','INDELC','RESELC','RESHOUSEELC','SERBUILDELC','SERDISTELC','SERELC') and (attribute = 'VAR_FOut' or attribute = 'VAR_FIn'); >> VedaBatchUpload.sql
echo COPY ( select analysis ^|^| '^|' ^|^| tablename ^|^| '^|' ^|^| attribute ^|^| '^|' ^|^| 'various^|various'::varchar(300) "id", analysis, tablename,attribute, 'various'::varchar(50) "commodity", 'various'::varchar(50) "process", sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from  >> VedaBatchUpload.sql
echo elecgen where analysis ^<^>'' group by id, analysis,tablename, attribute union select 'elec-gen_total' ^|^| '^|' ^|^| tablename ^|^| '^|' ^|^| attribute ^|^| '^|' ^|^| 'various^|various'::varchar(300) "id", 'elec-gen_total', tablename,attribute, 'various'::varchar(50) "commodity", 'various'::varchar(50) "process", sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", >> VedaBatchUpload.sql
echo sum(case when period='2055' then pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from elecgen where analysis in ('elec-gen_bio','elec-gen_bio-ccs','elec-gen_coal','elec-gen_coal-ccs','elec-gen_nga','elec-gen_nga-ccs','elec-gen_nuclear','elec-gen_offw','elec-gen_onw', 'elec-gen_other-ff','elec-gen_other-rens','elec-gen_solar') group by id, tablename, attribute union select 'elec-gen_inter' ^|^| '^|' ^|^| tablename ^|^| '^|' ^|^| 'various' ^|^| '^|' ^|^| 'various^|various'::varchar(300) "id", 'elec-gen_inter', tablename,'various'::varchar(50) "attribute", 'various'::varchar(50) "commodity", 'various'::varchar(50) "process", sum(case when analysis='elec-gen_imports' then pv else -pv end)::numeric "all", (sum(case when period='2010' and analysis='elec-gen_imports' then pv else 0 end)::numeric - sum(case when period='2010' and analysis='elec-gen_exports' then pv else 0 end)::numeric)::numeric"2010", (sum(case when period='2011' and analysis='elec-gen_imports' then pv else 0 end)::numeric - sum(case when period='2011' and analysis='elec-gen_exports' then pv else 0 end)::numeric)::numeric"2011", (sum(case when period='2012' and analysis='elec-gen_imports' then pv else 0 end)::numeric - sum(case when period='2012' and analysis='elec-gen_exports' then pv else 0 end)::numeric)::numeric"2012", (sum(case when period='2015' and analysis='elec-gen_imports' then pv else 0 end)::numeric - sum(case when period='2015' and analysis='elec-gen_exports' then pv else 0 end)::numeric)::numeric"2015", (sum(case when period='2020' >> VedaBatchUpload.sql
echo and analysis='elec-gen_imports' then pv else 0 end)::numeric - sum(case when period='2020' and analysis='elec-gen_exports' then pv else 0 end)::numeric)::numeric"2020", (sum(case when period='2025' and analysis='elec-gen_imports' then pv else 0 end)::numeric - sum(case when period='2025' and analysis='elec-gen_exports' then pv else 0 end)::numeric)::numeric"2025", (sum(case when period='2030' and analysis='elec-gen_imports' then pv else 0 end)::numeric - sum(case when period='2030' and analysis='elec-gen_exports' then pv else 0 end)::numeric)::numeric"2030", (sum(case when period='2035' and analysis='elec-gen_imports' then pv else 0 end)::numeric - sum(case when period='2035' and analysis='elec-gen_exports' then pv else 0 end)::numeric)::numeric"2035", (sum(case when period='2040' and analysis='elec-gen_imports' then pv else 0 end)::numeric - sum(case when period='2040' and analysis='elec-gen_exports' then pv else 0 end)::numeric)::numeric"2040", (sum(case when period='2045' and analysis='elec-gen_imports' then pv else 0 end)::numeric - sum(case when period='2045' and analysis='elec-gen_exports' then pv else 0 end)::numeric)::numeric"2045", (sum(case when period='2050' and analysis='elec-gen_imports' then pv else 0 end)::numeric - sum(case when period='2050' and analysis='elec-gen_exports' then pv else 0 end)::numeric)::numeric"2050", (sum(case when period='2055' and analysis='elec-gen_imports' then pv else 0 end)::numeric - sum(case when period='2055' and analysis='elec-gen_exports' then pv else 0 end)::numeric)::numeric"2055", (sum(case when period='2060' and analysis='elec-gen_imports' then pv else 0 end)::numeric - sum(case when period='2060' and analysis='elec-gen_exports' then pv else 0 end)::numeric)::numeric"2060" from elecgen where analysis in ('elec-gen_imports','elec-gen_exports') group by id, tablename order by tablename, analysis, attribute, commodity  ) TO '%~dp0ElecGenOut.csv' delimiter ',' CSV; >> VedaBatchUpload.sql
rem Elec storage
echo /* *Elec storage* */COPY ( select 'elec-stor^|' ^|^| tablename ^|^| '^|Var_FOut^|ELC^|various'::varchar(300) "id", 'elec-stor'::varchar(25) "analysis", tablename, 'VAR_FOut'::varchar "attribute", 'ELC'::varchar "commodity", 'various'::varchar(50) "process", sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from vedastore where attribute = 'VAR_FOut' and commodity = 'ELC' and process in('EHYDPMP00','EHYDPMP01','ECAESCON01','ESTGCAES01','ECAESTUR01','ESTGAACAES01','ESTGBNAS01','ESTGBALA01','ESTGBRF01') group by tablename ) TO '%~dp0ElecStor.csv' delimiter ',' CSV; >> VedaBatchUpload.sql
rem Electricity capacity by process
echo /* *Electricity capacity by process* */COPY ( select analysis ^|^| '^|' ^|^| tablename ^|^| '^|' ^|^| attribute ^|^| '^|' ^|^| '-^|various'::varchar(300) "id", analysis, tablename,attribute, '-'::varchar(50) "commodity", 'various'::varchar(50) "process", sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from ( select process, period,pv, case when process like 'ESTWWST00' or process like 'EPOLWST00' or process like 'EBIOS00' or process like 'EBOG-LFE00' or process like 'EBOG-SWE00' or process like 'EMSW00' or process like 'EBIOCON00' or process like 'ESTWWST01' or process like 'EBIO01' or process like 'EBOG-ADE01' or process like 'EBOG-LFE01' or process like 'EBOG-SWE01' or process like 'EMSW01' then 'elec-cap_bio'::varchar(50) when process like 'EBIOQ01' then 'elec-cap_bio-ccs'::varchar(50) when process like 'ECOA00' or process like 'ECOABIO00' or process like 'ECOARR01' then 'elec-cap_coal'::varchar(50) when process like 'ECOAQ01' or process like 'ECOAQDEMO01'  >> VedaBatchUpload.sql
echo then 'elec-cap_coal-ccs'::varchar(50) when process like 'EHYGCCT01' or process like 'EHYGOCT01' then 'elec-cap_h2'::varchar(50) when process like 'ENGACCT00' or process like 'ENGAOCT00' or process like 'ENGACCTRR01' or process like 'ENGAOCT01' then 'elec-cap_nga'::varchar(50) when process like 'ENGACCTQ01' or process like 'ENGACCTQDEMO01' then 'elec-cap_nga-ccs'::varchar(50) when process like 'ENUCPWR00' or process like 'ENUCAGRN00' or process like 'ENUCAGRO00' or process like 'ENUCPWR101' or process like 'ENUCPWR102' then 'elec-cap_nuclear'::varchar(50) when process like 'EWNDOFF00' or process like 'EWNDOFF101' or process like 'EWNDOFF201' or process like 'EWNDOFF301' then 'elec-cap_offw'::varchar(50) when process like 'EWNDONS00' or process like 'EWNDONS101' or process like 'EWNDONS201' or process like 'EWNDONS301' or process like 'EWNDONS401' or process like 'EWNDONS501' or process like 'EWNDONS601' or process like 'EWNDONS701' or process like 'EWNDONS801' or process like 'EWNDONS901' then 'elec-cap_onw'::varchar(50) when process like 'EHFOIGCCQ01' then 'elec-cap_other-ccs'::varchar(50) when process like 'EOILL00' or process like 'EOILS00' or process like 'EMANOCT00' or process like 'EMANOCT01' or process like 'EOILS01' or process like 'EOILL01' or process like 'EHFOIGCC01' then 'elec-cap_other-ff'::varchar(50) when process like 'EHYD00' or process like 'EHYD01' or process like 'EGEO01' or process like 'ETIR101' or process like 'ETIB101' or process like 'ETIS101' or process like 'EWAV101' then 'elec-cap_other-rens'::varchar(50) when  >> VedaBatchUpload.sql
echo process like 'ESOL00' or process like 'ESOLPV00' or process like 'ESOL01' or process like 'ESOLPV01' then 'elec-cap_solar'::varchar(50) when process like 'I%%CHP%%' or process like 'P%%CHP%%' or process like 'R%%CHP%%' or process like 'S%%CHP%%' or process like 'U%%CHP%%' then 'elec-cap_chp'::varchar(50) when process like 'ELCIE%%' or process like 'ELCII%%' then 'elec-cap_intercon'::varchar(50) else 'elec-cap_other' end as "analysis", tablename, attribute from vedastore where attribute = 'VAR_Cap' and commodity = '-' AND (process in('ESTWWST00','EPOLWST00','EBIOS00','EBOG-LFE00','EBOG-SWE00','EMSW00','EBIOCON00','ESTWWST01','EBIO01','EBOG-ADE01','EBOG-LFE01','EBOG-SWE01','EMSW01','EBIOQ01','ECOA00','ECOABIO00','ECOARR01','ECOAQ01','ECOAQDEMO01','EHYGCCT01','EHYGOCT01','ENGACCT00','ENGAOCT00','ENGACCTRR01','ENGAOCT01','ENGACCTQ01','ENGACCTQDEMO01','ENUCPWR00','ENUCAGRN00','ENUCAGRO00','ENUCPWR101','ENUCPWR102','EWNDOFF00','EWNDOFF101','EWNDOFF201','EWNDOFF301','EWNDONS00','EWNDONS101','EWNDONS201','EWNDONS301','EWNDONS401','EWNDONS501','EWNDONS601','EWNDONS701','EWNDONS801','EWNDONS901','EHFOIGCCQ01','EOILL00','EOILS00','EMANOCT00','EMANOCT01','EOILS01','EOILL01','EHFOIGCC01','EHYD00','EHYD01','EGEO01','ETIR101','ETIB101','ETIS101','EWAV101','ESOL00','ESOLPV00','ESOL01','ESOLPV01') or process like 'I%%CHP%%' or process like 'P%%CHP%%' or process like 'R%%CHP%%' or process like 'S%%CHP%%' or process like 'U%%CHP%%' or process like 'ELCIE%%' or process like 'ELCII%%') ) a group by id, analysis,tablename, attribute order by tablename, analysis, attribute, commodity ) TO '%~dp0ElecCap.csv' delimiter ',' CSV; >> VedaBatchUpload.sql
rem Biofuels by sector
echo /* *Biofuels by sector* */COPY ( select analysis ^|^| '^|' ^|^| tablename ^|^| '^|VAR_FIn^|' ^|^| commodity ^|^| '^|' ^|^| process::varchar(300) "id", analysis, tablename,attribute, commodity, process, sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from ( select left(process,3) ^|^| '*'::varchar(50) "process",period,pv, 'biofuels'::varchar(50) as "analysis", tablename, attribute,'various'::varchar(50) "commodity" from vedastore where attribute='VAR_FIn' and left(process,3) in('AGR','ELC','HYG','IND','PRC','RES','SER','TRA') ) a where analysis ^<^>'' group by id, analysis,tablename, attribute, commodity,process order by tablename, analysis, attribute, commodity ) TO '%~dp0BiofuelsOut.csv' delimiter ',' CSV; >> VedaBatchUpload.sql
rem /* *costs by sector and type* */
echo /* *costs by sector and type* */COPY ( select analysis ^|^| '^|' ^|^| tablename ^|^|'^|'^|^| attribute ^|^| '^|various' ^|^| '^|various'::varchar(300) "id", analysis, tablename,attribute, 'various'::varchar(50) "commodity", 'various'::varchar(50) "process", sum(pv)::numeric "various", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from ( select process, period,pv, case when process like 'T%%' then 'costs_tra'::varchar(50) when process like 'A%%' then 'costs_agr'::varchar(50) when process like 'E%%' AND process not like 'EXP%%' then 'costs_elc'::varchar(50) when process like 'I%%' AND process not like 'IMP%%' then 'costs_ind'::varchar(50) when process like 'P%%' or process like 'C%%' then 'costs_prc'::varchar(50) when process like 'R%%' then 'costs_res'::varchar(50) when process like 'M%%'or process like 'U%%'or process like 'IMP%%'or process like 'EXP%%' then 'costs_rsr'::varchar(50) when process like 'S%%' then 'costs_ser'::varchar(50) else 'costs_other'::varchar(50) end as "analysis",tablename, attribute from vedastore where attribute in('Cost_Act', 'Cost_Flo', 'Cost_Fom', 'Cost_Inv', 'Cost_Salv','ObjZ') group by period,process, pv,tablename, id, analysis, attribute ) a group by id, analysis, tablename, attribute order by tablename, analysis, attribute, commodity  ) TO '%~dp0CostsBySec.csv' delimiter ',' CSV; >> VedaBatchUpload.sql
rem /* *Marginal prices for emissions* */
echo /* *Marginal prices for emissions* */COPY ( select 'marg-price^|' ^|^| tablename ^|^| '^|VAR_ComnetM^|' ^|^| commodity ^|^| '^|-'::varchar(300) "id", 'marg-price'::varchar(50) "analysis", tablename, 'VAR_ComnetM'::varchar(50) "attribute", commodity, '-'::varchar(50) "process", NULL::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from vedastore where attribute='VAR_ComnetM' and commodity in('GHG-NO-IAS-YES-LULUCF-NET','GHG-ETS-NO-IAS-NET','GHG-YES-IAS-YES-LULUCF-NET','GHG-ETS-YES-IAS-NET') group by tablename, commodity order by tablename, commodity  ) TO '%~dp0MarginalPricesOut.csv' delimiter ',' CSV; >> VedaBatchUpload.sql
rem /* *Whole stock heat output by process for residential* */
echo /* *Whole stock heat output by process for residential* */COPY ( select analysis ^|^| '^|' ^|^| tablename ^|^| '^|' ^|^| attribute ^|^| '^|' ^|^| 'various^|various'::varchar(300) "id", analysis, tablename,attribute, 'various'::varchar(50) "commodity", 'various'::varchar(50) "process", sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from ( select process, period,pv, case when process like 'RH%%CSV%%' then 'heat-res_conserv'::varchar(50) when  >> VedaBatchUpload.sql
echo process like 'RH%%DHP%%' then 'heat-res_dh'::varchar(50) when process like 'RH%%CHPRW01' then 'heat-res_microchp_bio'::varchar(50) when process like 'RH%%CHPRG01' then 'heat-res_microchp_nga'::varchar(50) when process like 'RH%%BLCRH01' or process like 'RH%%BLSRH01' then 'heat-res_boiler_h2'::varchar(50) when process like 'RH%%CHPRH01' or process like 'RH%%CHBRH01' then 'heat-res_microchp_h2'::varchar(50) when process like 'RH%%STGNT00' or process like 'RH%%NSTRE00' or process like 'RH%%STGNT01' or process like 'RH%%NSTRE01' then 'heat-res_storheater_elec'::varchar(50) when process like 'RH%%AHHRE01' or process like 'RH%%AHHUE01' or process like 'RH%%GHHRE01' or process like 'RH%%GHHUE01' then 'heat-res_hyb-boil+hp_h2'::varchar(50) when process like 'RH%%AHBRE01' or process like 'RH%%AHBUE01' or process like 'RH%%GHBRE01' or process like 'RH%%GHBUE01' then 'heat-res_hyb-boil+hp_nga'::varchar(50) when process like 'RH%%BLRRW00' or process like 'RH%%BLCRP01' or process like 'RH%%BLRRW01' or process like 'RH%%BLSRP01' or process like 'RH%%BLSRW01' then 'heat-res_boiler_bio'::varchar(50) when process like 'RH%%BLRRO00' or process like 'RH%%BLCRO00' or process like 'RH%%BLRRC00' or process >> VedaBatchUpload.sql
echo  like 'RH%%BLCRO01' or process like 'RH%%BLSRO01' then 'heat-res_boiler_otherFF'::varchar(50) when process like 'RH%%AHPRE00' or process like 'RH%%AHPRE01' or process like 'RH%%AHPUE01' or process like 'RH%%GHPRE01' or process like 'RH%%GHSUE01' or process like 'RH%%AHSRE01' or process like 'RH%%AHSUE01' or process like 'RH%%GHSRE01' then 'heat-res_heatpump_elec'::varchar(50) when process like 'RH%%BLRRE00' or process like 'RH%%SHTRE00' or process like 'RW%%WHTRE00' or process like 'RH%%BLRRE01' or process like 'RH%%GHPUE01' or process like 'RH%%SHTRE01' or process like 'RW%%WHTRE01' or process like 'RH%%BLSRE01' then 'heat-res_boiler/heater_elec'::varchar(50) when process like 'RH%%BLRRG00' or process like 'RH%%BLCRG00' or process like 'RH%%SHTRG00' or process like 'RW%%WHTRG00' or process like 'RW%%SOLRS00' or process like 'RH%%BLCRG01' or process like 'RH%%SHTRG01' or process like 'RW%%WHTRG01' or process like 'RH%%BLSRG01' then 'heat-res_boiler/heater_nga'::varchar(50) else 'heat-res_other' end as "analysis", tablename, attribute from vedastore where attribute = 'VAR_FOut' AND (commodity like 'RHEATPIPE-%%' or commodity like 'RHUFLOOR-%%' or commodity like 'RHSTAND-%%' or commodity like 'RWSTAND-%%' or commodity like 'RHCSV-RH%%' or commodity like 'RWCSV-RW%%') group by period,process, pv,tablename, id, analysis, attribute order by tablename, attribute ) a group by id, analysis,tablename, attribute order by tablename, analysis, attribute, commodity  ) TO '%~dp0ResWholeHeatOut.csv' delimiter ',' CSV; >> VedaBatchUpload.sql
rem /* *New build residential heat output by source* */
echo /* *New build residential heat output by source* */COPY ( select analysis ^|^| '^|' ^|^| tablename ^|^| '^|' ^|^| attribute ^|^| '^|' ^|^| 'various^|various'::varchar(300) "id", analysis, tablename,attribute, 'various'::varchar(50) "commodity", 'various'::varchar(50) "process", sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from ( select process,commodity, period,pv, case   when process like 'RH%%CSV%%' then 'new-heat-res_conserv'::varchar(50)   when process like 'RH%%DHP%%' then 'new-heat-res_dh'::varchar(50)   when process like 'RH%%CHPRW01' then 'new-heat-res_microchp_bio'::varchar(50)   when process like 'RH%%CHPRG01'  >> VedaBatchUpload.sql
echo then 'new-heat-res_microchp_nga'::varchar(50)   when process like 'RH%%BLCRH01' or process like 'RH%%BLSRH01' then 'new-heat-res_boiler_h2'::varchar(50)   when process like 'RH%%CHPRH01' or process like 'RH%%CHBRH01' then 'new-heat-res_microchp_h2'::varchar(50)   when process like 'RH%%STGNT00' or process like 'RH%%NSTRE00' or process like 'RH%%STGNT01' or process like 'RH%%NSTRE01' then 'new-heat-res_storheater_elec'::varchar(50)   when process like 'RH%%AHHRE01' or process like 'RH%%AHHUE01' or process like 'RH%%GHHRE01' or process like 'RH%%GHHUE01' then 'new-heat-res_hyb-boil+hp_h2'::varchar(50)   when process like 'RH%%AHBRE01' or process like 'RH%%AHBUE01' or process like 'RH%%GHBRE01' or process like 'RH%%GHBUE01' then 'new-heat-res_hyb-boil+hp_nga'::varchar(50)   when process like 'RH%%BLRRW00' or process like 'RH%%BLCRP01' or process like 'RH%%BLRRW01' or process like 'RH%%BLSRP01' or     process like 'RH%%BLSRW01' then 'new-heat-res_boiler_bio'::varchar(50)   when process like 'RH%%BLRRO00' or process like 'RH%%BLCRO00' or process like 'RH%%BLRRC00' or process like 'RH%%BLCRO01' or     process like 'RH%%BLSRO01' then 'new-heat-res_boiler_otherFF'::varchar(50)   when process like 'RH%%AHPRE00' or process  >> VedaBatchUpload.sql
echo like 'RH%%AHPRE01' or process like 'RH%%AHPUE01' or process like 'RH%%GHPRE01' or     process like 'RH%%GHSUE01' or process like 'RH%%AHSRE01' or process like 'RH%%AHSUE01' or process like 'RH%%GHSRE01' then 'new-heat-res_heatpump_elec'::varchar(50)   when process like 'RH%%BLRRE00' or process like 'RH%%SHTRE00' or process like 'RW%%WHTRE00' or process like 'RH%%BLRRE01' or     process like 'RH%%GHPUE01' or process like 'RH%%SHTRE01' or process like 'RW%%WHTRE01' or process like 'RH%%BLSRE01' then 'new-heat-res_boiler/heater_elec'::varchar(50)   when process like 'RH%%BLRRG00' or process like 'RH%%BLCRG00' or process like 'RH%%SHTRG00' or process like 'RW%%WHTRG00' or     process like 'RW%%SOLRS00' or process like 'RH%%BLCRG01' or process like 'RH%%SHTRG01' or process like 'RW%%WHTRG01' or     process like 'RH%%BLSRG01' then 'new-heat-res_boiler/heater_nga'::varchar(50) end as "analysis", tablename, attribute from vedastore where attribute = 'VAR_FOut' AND (commodity like 'RHEATPIPE-%%' or commodity like 'RHUFLOOR-%%' or commodity like 'RHSTAND-%%' or commodity like 'RWSTAND-%%' or commodity like 'RHCSV-RH%%' or commodity like 'RWCSV-RW%%') and vintage=period group by period,commodity,process, pv,tablename, id, analysis, attribute order by tablename, attribute ) a where analysis ^<^> '' group by id, analysis,tablename, attribute order by tablename, analysis, attribute, commodity  ) TO '%~dp0NewResHeatOut.csv' delimiter ',' CSV; >> VedaBatchUpload.sql
rem /* *Whole stock heat output for services* */
echo /* *Whole stock heat output for services* */COPY ( select analysis ^|^| '^|' ^|^| tablename ^|^| '^|' ^|^| attribute ^|^| '^|' ^|^| 'various^|various'::varchar(300) "id", analysis, tablename,attribute, 'various'::varchar(50) "commodity", 'various'::varchar(50) "process", sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from ( select process, period,pv, case when process in ('SHLSHTRE00','SWLWHTRE00','SHLBLRRE01','SHLSHTRE01','SWLWHTRE01','SHLBLSRE01','SHHBLRRE00','SWHWHTRE00','SHHBLRRE01','SWHWHTRE01','SHLBLRRE00') then 'heat-ser_boiler/heater_elec' when process in('SHLBLCRG00','SHLSHTRG00','SWLWHTRG00','SHLBLCRG01', >> VedaBatchUpload.sql
echo 'SWLWHTRG01','SHLBLSRG01','SHHBLRRG00','SWHBLRRG00','SHHBLRRG01','SWHBLRRG01','SHLBLRRG00') then 'heat-ser_boiler/heater_nga' when process in('SHLBLCRP01','SHLBLRRW01','SHLBLSRP01','SHLBLSRW01','SHHBLRRW00','SWHBLRRW00','SHHBLRRW01','SWHBLRRW01','SHLBLRRW00') then 'heat-ser_boiler_bio' when process in('SHLBLSRH01','SHHBLRRH01','SWHBLRRH01','SHLBLCRH01') then 'heat-ser_boiler_h2' when process in('SHLBLCRO00','SHLBLRRC00','SHLSHTRO00','SHLBLCRO01','SHLBLSRO01','SHHBLRRO00','SHHBLRRC00','SWHBLRRO00','SWHBLRRC00','SHHBLRRO01','SHHBLRRC01','SWHBLRRO01','SWHBLRRC01','SHLBLRRO00') then 'heat-ser_boiler_otherFF' when process in('SCSLROFF01','SCSLROFP01','SCSLCAVW01','SCSHPTHM01','SCSHROFF01','SCSHROFP01','SCSHCAVW01','SCSLPTHM01') then 'heat-ser_conserv' when process in('SHLAHBUE01','SHLGHBRE01','SHLGHBUE01','SHLAHBRE01') then 'heat-ser_hyb-boil+hp_nga' when process in('SHLAHPRE01','SHLAHPUE01','SHLGHPRE01','SHLGHPUE01','SHLAHSRE01','SHLAHSUE01','SHLGHSRE01', >> VedaBatchUpload.sql
echo 'SHLGHSUE01','SHLAHPRE00') then 'heat-ser_heatpump_elec' when process in('SHHVACAE01','SHHVACAE00') then 'heat-ser_hvac' when process in('SHHVACAE02') then 'heat-ser_hvac-ad' when process in('SHLAHHUE01','SHLGHHRE01','SHLGHHUE01','SHLAHHRE01') then 'heat-ser_hyb-boil+hp_h2' when process in('SHLDHP101','SHHDHP100','SHHDHP101','SHLDHP100') then 'heat-ser_dh' when process in('SHLCHPRW01') then 'heat-ser_microchp_bio' when process in('SHLCHBRH01','SHHFCLRH01','SHLCHPRH01') then 'heat-ser_microchp_h2' when process in('SHLCHPRG01') then 'heat-ser_microchp_nga' when process in('SHLNSTRE01','SHLNSTRE00') then 'heat-ser_storheater_elec' else 'heat-ser_other' end as "analysis", tablename, attribute from vedastore where attribute = 'VAR_FOut' AND commodity in('SHHCSVDMD','SHHDELVAIR','SHHDELVRAD','SHLCSVDMD','SHLDELVAIR','SHLDELVRAD','SHLDELVUND','SWHDELVPIP','SWHDELVSTD','SWLDELVSTD') group by period,process, pv,tablename, id, analysis, attribute order by tablename, attribute ) a group by id, analysis,tablename, attribute order by tablename, analysis, attribute, commodity  ) TO '%~dp0ServWholeHeatOut.csv' delimiter ',' CSV; >> VedaBatchUpload.sql
rem /* *New build services heat output by source* */
echo /* *New build services heat output by source* */COPY ( select analysis ^|^| '^|' ^|^| tablename ^|^| '^|' ^|^| attribute ^|^| '^|' ^|^| 'various^|various'::varchar(300) "id", analysis, tablename,attribute, 'various'::varchar(50) "commodity", 'various'::varchar(50) "process", sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from ( select process, period,pv, case when process in ('SHLSHTRE00','SWLWHTRE00','SHLBLRRE01','SHLSHTRE01', >> VedaBatchUpload.sql
echo 'SWLWHTRE01','SHLBLSRE01','SHHBLRRE00','SWHWHTRE00','SHHBLRRE01','SWHWHTRE01','SHLBLRRE00') then 'new-heat-ser_boiler/heater_elec' when process in('SHLBLCRG00','SHLSHTRG00','SWLWHTRG00','SHLBLCRG01','SWLWHTRG01','SHLBLSRG01','SHHBLRRG00','SWHBLRRG00','SHHBLRRG01','SWHBLRRG01','SHLBLRRG00') then 'new-heat-ser_boiler/heater_nga' when process in('SHLBLCRP01','SHLBLRRW01','SHLBLSRP01','SHLBLSRW01','SHHBLRRW00','SWHBLRRW00','SHHBLRRW01','SWHBLRRW01','SHLBLRRW00') then 'new-heat-ser_boiler_bio' when process in('SHLBLSRH01','SHHBLRRH01','SWHBLRRH01','SHLBLCRH01') then 'new-heat-ser_boiler_h2' when process in('SHLBLCRO00','SHLBLRRC00','SHLSHTRO00','SHLBLCRO01','SHLBLSRO01','SHHBLRRO00','SHHBLRRC00','SWHBLRRO00','SWHBLRRC00','SHHBLRRO01','SHHBLRRC01','SWHBLRRO01','SWHBLRRC01','SHLBLRRO00') then 'new-heat-ser_boiler_otherFF' when process in('SCSLROFF01','SCSLROFP01','SCSLCAVW01','SCSHPTHM01','SCSHROFF01','SCSHROFP01','SCSHCAVW01','SCSLPTHM01') then 'new-heat-ser_conserv' when process in('SHLAHBUE01','SHLGHBRE01','SHLGHBUE01','SHLAHBRE01') then 'new-heat-ser_hyb-boil+hp_nga'  >> VedaBatchUpload.sql
echo when process in('SHLAHPRE01','SHLAHPUE01','SHLGHPRE01','SHLGHPUE01','SHLAHSRE01','SHLAHSUE01','SHLGHSRE01','SHLGHSUE01','SHLAHPRE00') then 'new-heat-ser_heatpump_elec' when process in('SHHVACAE01','SHHVACAE00') then 'new-heat-ser_hvac' when process in('SHHVACAE02') then 'new-heat-ser_hvac-ad' when process in('SHLAHHUE01','SHLGHHRE01','SHLGHHUE01','SHLAHHRE01') then 'new-heat-ser_hyb-boil+hp_h2' when process in('SHLDHP101','SHHDHP100','SHHDHP101','SHLDHP100') then 'new-heat-ser_dh' when process in('SHLCHPRW01') then 'new-heat-ser_microchp_bio' when process in('SHLCHBRH01','SHHFCLRH01','SHLCHPRH01') then 'new-heat-ser_microchp_h2' when process in('SHLCHPRG01') then 'new-heat-ser_microchp_nga' when process in('SHLNSTRE01','SHLNSTRE00') then 'new-heat-ser_storheater_elec' else 'new-new-heat-ser_other' end as "analysis", tablename, attribute from vedastore where attribute = 'VAR_FOut' AND commodity in('SHHCSVDMD','SHHDELVAIR','SHHDELVRAD','SHLCSVDMD','SHLDELVAIR','SHLDELVRAD','SHLDELVUND','SWHDELVPIP','SWHDELVSTD','SWLDELVSTD') and vintage=period group by period,process, pv,tablename, id, analysis, attribute order by tablename, attribute ) a group by id, analysis,tablename, attribute order by tablename, analysis, attribute, commodity  ) TO '%~dp0NewServHeatOut.csv' delimiter ',' CSV; >> VedaBatchUpload.sql
rem /* *Whole stock vehicle kms, emissions for 19 vehicle types and CNG use (car, lgv, hgv)* */
echo /* *Whole stock vehicle kms, emissions for 19 vehicle types and CNG use (car, lgv, hgv)* */COPY ( select analysis ^|^| '^|' ^|^| tablename ^|^| '^|' ^|^| attribute ^|^| '^|' ^|^| commodity ^|^| '^|various'::varchar(300) "id", analysis, tablename,attribute, commodity, 'various'::varchar(50) "process", sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then  >> VedaBatchUpload.sql
echo pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from ( select process, period,pv,vintage, case when left(process, 2)='TC' then 'cars-' when left(process, 2)='TL' then 'lgv-' when left(process, 2)='TH' then 'hgv-' end ^|^| case when commodity in('TC','TL','TH') then 'km_' when commodity like 'GHG-%%' then 'emis_' end ^|^| case when process like '%%PHBPET01' or process like '%%PHBDST01' then 'plug-in-hybrid'::varchar(50) when process like '%%HBPET00' or process like '%%HBPET01' or process like '%%HBDST01' then 'hybrid'::varchar(50) when process like '%%DST00' or process like '%%DST01' then 'diesel'::varchar(50) when process like '%%ELC01' then 'electric'::varchar(50) when process like '%%FCHYG01' or process like '%%FCHBHYG01' or process like '%%HBHYL01' then 'h2+hybrid'::varchar(50) when process like '%%FCPHBHYG01' then 'h2-plug-in-hybrid'::varchar(50) when process like '%%LPG00' or process like '%%LPG01' or process like '%%CNG01' then 'lpg-and-cng-fueled'::varchar(50) when process like '%%PET00' or process like '%%PET01' or process like '%%E8501' then 'petrol'::varchar(50) end as "analysis", tablename, attribute,commodity from vedastore where attribute = 'VAR_FOut' and (commodity in('TC','TL','TH') or commodity like 'GHG-%%') and (process like 'TC%%' or process like ('TL%%') or process !textc!'!textd!TH[!textd!Y]') ) a where analysis ^<^>'' group by id, analysis, >> VedaBatchUpload.sql
echo tablename, attribute, commodity union select analysis ^|^| '^|' ^|^| tablename ^|^| '^|' ^|^| attribute ^|^| '^|' ^|^| commodity ^|^| '^|' ^|^| process::varchar(300) "id", analysis, tablename,attribute, commodity, process, sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from ( select case when process = 'TFSSCNG01' then 'TFSSCNG01' else left(process,2) ^|^| '%%'::varchar(50) end as process, period,pv, case when process = 'TFSSCNG01' and attribute ='VAR_FOut' and commodity like 'GHG-%%' then 'cars-cng-conv-emis' when attribute = 'VAR_FIn' then case when process like 'TC%%' then 'cars-cng-in' when process like 'TL%%' then 'lgv-cng-in' when process like 'TH%%' then 'hgv-cng-in' end end as "analysis", tablename, attribute,commodity from vedastore where (attribute = 'VAR_FIn' or attribute ='VAR_FOut') and (commodity = 'TRACNGS' or commodity like 'GHG-%%') and (process = 'TFSSCNG01' or process like 'TC%%' or process like 'TL%%' or process like 'TH%%') ) a where analysis ^<^>'' group by id, analysis,tablename, attribute, commodity, process  ) TO '%~dp0vehKms.csv' delimiter ',' CSV; >> VedaBatchUpload.sql
rem /* *New vehicle kms, emissions for 19 vehicle types and CNG use (car, lgv, hgv)* */
echo /* *New vehicle kms, emissions for 19 vehicle types and CNG use (car, lgv, hgv)* */COPY ( select analysis ^|^| '^|' ^|^| tablename ^|^| '^|' ^|^| attribute ^|^| '^|' ^|^| commodity ^|^| '^|various'::varchar(300) "id", analysis, tablename,attribute, commodity, 'various'::varchar(50) "process", sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from ( select process, period,pv,vintage, case when left(process, 2)='TC' then 'cars-new-' when left(process, 2)='TL' then 'lgv-new-' when left(process, 2)='TH' then 'hgv-new-' end ^|^| case when commodity in('TC','TL','TH') then 'km_' when commodity like 'GHG-%%' then 'emis_' end ^|^|  >> VedaBatchUpload.sql
echo case when process like '%%PHBPET01' or process like '%%PHBDST01' then 'plug-in-hybrid'::varchar(50) when process like '%%HBPET00' or process like '%%HBPET01' or process like '%%HBDST01' then 'hybrid'::varchar(50) when process like '%%DST00' or process like '%%DST01' then 'diesel'::varchar(50) when process like '%%ELC01' then 'electric'::varchar(50) when process like '%%FCHYG01' or process like '%%FCHBHYG01' or process like '%%HBHYL01' then 'h2+hybrid'::varchar(50) when process like '%%FCPHBHYG01' then 'h2-plug-in-hybrid'::varchar(50) when process like '%%LPG00' or process like '%%LPG01' or process like '%%CNG01' then 'lpg-and-cng-fueled'::varchar(50) when process like '%%PET00' or process like '%%PET01' or process like '%%E8501' then 'petrol'::varchar(50) end as "analysis", tablename, attribute,commodity from vedastore where attribute = 'VAR_FOut' and (commodity in('TC','TL','TH') or commodity like 'GHG-%%') and (process like 'TC%%' or process like ('TL%%') or process !textc!'!textd!TH[!textd!Y]') and right(process,2)='01' and vintage=period ) a where analysis ^<^>'' group by id, analysis,tablename, attribute, commodity union select analysis ^|^| '^|' ^|^| tablename ^|^| '^|' ^|^| attribute ^|^| '^|' ^|^| commodity ^|^| '^|' ^|^| process::varchar(300) "id", analysis, tablename,attribute, commodity, process, sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end):: >> VedaBatchUpload.sql
echo numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055", sum(case when period='2060' then pv else 0 end)::numeric "2060" from ( select left(process,2) ^|^| '%%'::varchar(50) as process, period,pv,vintage, case when process like 'TC%%' then 'cars-new-cng-in' when process like 'TL%%' then 'lgv-new-cng-in' when process like 'TH%%' then 'hgv-new-cng-in' end as "analysis", tablename, attribute,commodity from vedastore where attribute = 'VAR_FIn' and (commodity = 'TRACNGS' or commodity like 'GHG-%%') and left(process,2) in ('TC','TL','TH') and right(process,2)='01' and vintage=period ) a where analysis ^<^>'' group by id, analysis,tablename, attribute, commodity, process ) TO '%~dp0newVehKms.csv' delimiter ',' CSV; >> VedaBatchUpload.sql
rem /* *Whole stock capacity for vehicles for 19 vehicle types* */
echo /* *Whole stock capacity for vehicles for 19 vehicle types* */COPY ( select analysis ^|^| '^|' ^|^| tablename ^|^| '^|' ^|^| attribute ^|^| '^|' ^|^| commodity ^|^| '^|various'::varchar(300) "id", analysis, tablename,attribute, commodity, 'various'::varchar(50) "process", sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055",  >> VedaBatchUpload.sql
echo sum(case when period='2060' then pv else 0 end)::numeric "2060" from ( select process,period,pv, case when left(process, 2)='TC' then 'cars-cap_' when left(process, 2)='TL' then 'lgv-cap_' when left(process, 2)='TH' then 'hgv-cap_' end ^|^| case when process like '%%PHBPET01' or process like '%%PHBDST01' then 'plug-in-hybrid'::varchar(50) when process like '%%HBPET00' or process like '%%HBPET01' or process like '%%HBDST01' then 'hybrid'::varchar(50) when process like '%%DST00' or process like '%%DST01' then 'diesel'::varchar(50) when process like '%%ELC01' then 'electric'::varchar(50) when process like '%%FCHYG01' or process like '%%FCHBHYG01' or process like '%%HBHYL01' then 'h2+hybrid'::varchar(50) when process like '%%FCPHBHYG01' then 'h2-plug-in-hybrid'::varchar(50) when process like '%%LPG00' or process like '%%LPG01' or process like '%%CNG01' then 'lpg-and-cng-fueled'::varchar(50) when process like '%%PET00' or process like '%%PET01' or process like '%%E8501' then 'petrol'::varchar(50) end as "analysis", tablename, attribute,commodity from vedastore where attribute = 'VAR_Cap' and left(process,2) in('TC','TL','TH') ) a where analysis ^<^>'' group by id, analysis,tablename, attribute, commodity order by tablename, analysis, attribute, commodity ) TO '%~dp0VehCapOut.csv' delimiter ',' CSV; >> VedaBatchUpload.sql
rem /* *New build vehicle capacity for 19 vehicle types*/
echo /* *New build vehicle capacity for 19 vehicle types*/COPY ( select analysis ^|^| '^|' ^|^| tablename ^|^| '^|' ^|^| attribute ^|^| '^|' ^|^| commodity ^|^| '^|various'::varchar(300) "id", analysis, tablename,attribute, commodity, 'various'::varchar(50) "process", sum(pv)::numeric "all", sum(case when period='2010' then pv else 0 end)::numeric "2010", sum(case when period='2011' then pv else 0 end)::numeric "2011", sum(case when period='2012' then pv else 0 end)::numeric "2012", sum(case when period='2015' then pv else 0 end)::numeric "2015", sum(case when period='2020' then pv else 0 end)::numeric "2020", sum(case when period='2025' then pv else 0 end)::numeric "2025", sum(case when period='2030' then pv else 0 end)::numeric "2030", sum(case when period='2035' then pv else 0 end)::numeric "2035", sum(case when period='2040' then pv else 0 end)::numeric "2040", sum(case when period='2045' then pv else 0 end)::numeric "2045", sum(case when period='2050' then pv else 0 end)::numeric "2050", sum(case when period='2055' then pv else 0 end)::numeric "2055",  >> VedaBatchUpload.sql
echo sum(case when period='2060' then pv else 0 end)::numeric "2060" from ( select process,period,pv, case when process like 'TC%%' then 'cars-new-cap_' when process like 'TL%%' then 'lgv-new-cap_' when process like 'TH%%' then 'hgv-new-cap_' end ^|^| case when process like '%%PHBPET01' or process like '%%PHBDST01' then 'plug-in-hybrid'::varchar(50) when process like '%%HBPET00' or process like '%%HBPET01' or process like '%%HBDST01' then 'hybrid'::varchar(50) when process like '%%DST00' or process like '%%DST01' then 'diesel'::varchar(50) when process like '%%ELC01' then 'electric'::varchar(50) when process like '%%FCHYG01' or process like '%%FCHBHYG01' or process like '%%HBHYL01' then 'h2+hybrid'::varchar(50) when process like '%%FCPHBHYG01' then 'h2-plug-in-hybrid'::varchar(50) when process like '%%LPG00' or process like '%%LPG01' or process like '%%CNG01' then 'lpg-and-cng-fueled'::varchar(50) when process like '%%PET00' or process like '%%PET01' or process like '%%E8501' then 'petrol'::varchar(50) end as "analysis", tablename, attribute,commodity from vedastore where attribute='VAR_Ncap' and (process like 'TC%%' or process like ('TL%%') or process !textc!'!textd!TH[!textd!Y]') ) a where analysis ^<^>'' group by id, analysis,tablename, attribute, commodity order by tablename, analysis, attribute, commodity ) TO '%~dp0newVehCapOut.csv' delimiter ',' CSV; >> VedaBatchUpload.sql
rem following line actually runs the SQL code generated by the above using the postgres command utility "psql".
rem Comment this line out if you just want the SQL code to create the populated temp tables + the associated analysis queries:
"C:\Program Files\PostgreSQL\9.4\bin\psql.exe" -h localhost -p 5432 -U postgres -d gams -f %~dp0VedaBatchUpload.sql
rem following concatenates individual results to the GHGout.csv
type GHGOut.csv >> dummiesout.csv
type GHGsectorOut.csv >> dummiesout.csv
type CHPelecEmis.csv >> dummiesout.csv
type ElecGenOut.csv >> dummiesout.csv
type ElecStor.csv >> dummiesout.csv
type ElecCap.csv >> dummiesout.csv
type BiofuelsOut.csv >> dummiesout.csv
type CostsBySec.csv >> dummiesout.csv
type MarginalPricesOut.csv >> dummiesout.csv
type ResWholeHeatOut.csv >> dummiesout.csv
type NewResHeatOut.csv >> dummiesout.csv
type ServWholeHeatOut.csv >> dummiesout.csv
type NewServHeatOut.csv >> dummiesout.csv
type vehKms.csv >> dummiesout.csv
type newVehKms.csv >> dummiesout.csv
type VehCapOut.csv >> dummiesout.csv
type newVehCapOut.csv >> dummiesout.csv
rem before deleting the individual files and renaming dummiesout as ResultsOut
IF EXIST ResultsOut.csv del /F ResultsOut.csv
IF EXIST GHGOut.csv del /F GHGOut.csv
IF EXIST GHGsectorOut.csv del /F GHGsectorOut.csv
IF EXIST CHPelecEmis.csv del /F CHPelecEmis.csv
IF EXIST ElecGenOut.csv del /F ElecGenOut.csv
IF EXIST ElecStor.csv del /F ElecStor.csv
IF EXIST ElecCap.csv del /F ElecCap.csv
IF EXIST BiofuelsOut.csv del /F BiofuelsOut.csv
IF EXIST CostsBySec.csv del /F CostsBySec.csv
IF EXIST MarginalPricesOut.csv del /F MarginalPricesOut.csv
IF EXIST ResWholeHeatOut.csv del /F ResWholeHeatOut.csv
IF EXIST NewResHeatOut.csv del /F NewResHeatOut.csv
IF EXIST ServWholeHeatOut.csv del /F ServWholeHeatOut.csv
IF EXIST NewServHeatOut.csv del /F NewServHeatOut.csv
IF EXIST vehKms.csv del /F vehKms.csv
IF EXIST newVehKms.csv del /F newVehKms.csv
IF EXIST VehCapOut.csv del /F VehCapOut.csv
IF EXIST newVehCapOut.csv del /F newVehCapOut.csv
rename dummiesout.csv ResultsOut.csv
rem finally, delete dummiesout.csv if it exists
IF EXIST dummiesout.csv del /F dummiesout.csv